[build]
  command = """
    if [ ! -d "$HOME/flutter" ]; then
      git clone --depth 1 https://github.com/flutter/flutter.git -b stable $HOME/flutter
    fi
    export PATH="$HOME/flutter/bin:$PATH"
    flutter --version
    flutter config --no-analytics
    flutter pub get
    flutter build web --release --dart-define=SUPABASE_URL=$SUPABASE_URL --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
  """
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
